name: CI Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  package:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Empacotar com Maven
        run: mvn package  # Correção: 'run' dentro do mesmo passo

  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Deploy simulação
        run: echo "Deploy realizado com sucesso"