name: Lint and Test

on:
  workflow_call:
    inputs:
      run_lint:
        required: true
        type: boolean
        description: Executar lint?
      run_tests:
        required: true
        type: boolean
        description: Executar testes?
