name: Lint and Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Verificar estilo do código (Lint)
        run: echo "Lint executado com sucesso"

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Rodar testes automatizados
        run: echo "Testes executados com sucesso"
