name: Lint and Test

on:
  workflow_call:
    inputs:
      run_lint:
        description: 'Executar Lint?'
        required: true
        type: boolean
      run_tests:
        description: 'Executar Testes?'
        required: true
        type: boolean

jobs:
  lint:
    if: ${{ inputs.run_lint }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Executando Lint..."

  test:
    if: ${{ inputs.run_tests }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Executando Testes..."
